/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ContractCallArgs =
  | ChangeOwner
  | ClaimVault
  | ContractSourceMetadata
  | FtOnTransfer
  | GetCountdownPeriod
  | GetCountdownPeriodWithdraw
  | GetCurrentTimestamp
  | GetEndDate
  | GetFtTokenId
  | GetHighestDeposit
  | GetHighestWithdraw
  | GetLastDeposit
  | GetLastVault
  | GetListDeposits
  | GetNumberDeposits
  | GetTimeLastDeposit
  | GetTreasuryId
  | GetVaultBalance
  | GetVaults
  | GetVaultsNumber
  | IsTheOwner
  | New
  | SetCountdownPeriodWithdraw
  | SetTreasury
  | GetGreeting;
/**
 * NEAR Account Identifier.
 *
 * This is a unique, syntactically valid, human-readable account identifier on the NEAR network.
 *
 * [See the crate-level docs for information about validation.](index.html#account-id-rules)
 *
 * Also see [Error kind precedence](AccountId#error-kind-precedence).
 *
 * ## Examples
 *
 * ``` use near_account_id::AccountId;
 *
 * let alice: AccountId = "alice.near".parse().unwrap();
 *
 * assert!("ƒelicia.near".parse::<AccountId>().is_err()); // (ƒ is not f) ```
 */
export type AccountId = string;

export interface GetGreeting {}

export interface ChangeOwner {
  new_owner_id: AccountId;
}
export interface ClaimVault {
  index: number;
}
export interface ContractSourceMetadata {}
export interface FtOnTransfer {
  sender_id: AccountId;
  amount: string;
  msg: string;
}
export interface GetCountdownPeriod {}
export interface GetCountdownPeriodWithdraw {}
export interface GetCurrentTimestamp {}
export interface GetEndDate {}
export interface GetFtTokenId {}
export interface GetHighestDeposit {}
export interface GetHighestWithdraw {}
export interface GetLastDeposit {}
export interface GetLastVault {}
export interface GetListDeposits {
  from_index: number;
  limit: number;
}
export interface GetNumberDeposits {}
export interface GetTimeLastDeposit {}
export interface GetTreasuryId {}
export interface GetVaultBalance {}
export interface GetVaults {
  start_index: number;
  limit: number;
}
export interface GetVaultsNumber {}
export interface IsTheOwner {}
export interface New {
  ft_token_id: AccountId;
  countdown_period_withdraw: number;
  owner_id: AccountId;
  treasury_id: AccountId;
  treasury_fee: number;
}
export interface SetCountdownPeriodWithdraw {
  new_countdown: number;
}
export interface SetTreasury {
  new_treasury_id: AccountId;
}
